// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug: Log environment variable status (without exposing full key)
// Log in both dev and prod to help debug Vercel issues
console.log('🔍 Supabase Configuration Check:');
console.log('   Environment:', import.meta.env.MODE);
console.log('   URL:', SUPABASE_URL ? `✅ Set (${SUPABASE_URL.substring(0, 30)}...)` : '❌ NOT SET');
console.log('   Key:', SUPABASE_PUBLISHABLE_KEY ? `✅ Set (${SUPABASE_PUBLISHABLE_KEY.length} chars)` : '❌ NOT SET');

if (SUPABASE_PUBLISHABLE_KEY) {
  // Check if key starts with quotes (common .env issue)
  if (SUPABASE_PUBLISHABLE_KEY.startsWith('"') || SUPABASE_PUBLISHABLE_KEY.startsWith("'")) {
    console.warn('⚠️ Key appears to have quotes - this may cause issues. Remove quotes from .env file.');
  }
}

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL is not set. Please add it to your .env file.');
  console.error('   Expected: VITE_SUPABASE_URL=https://flndlrgxxnlhuuusargv.supabase.co');
  console.error('   For Vercel: Add this in Project Settings > Environment Variables');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY is not set. Please add it to your .env file.');
  console.error('   Get your anon/publishable key from: https://supabase.com/dashboard/project/flndlrgxxnlhuuusargv/settings/api');
  console.error('   For Vercel: Add this in Project Settings > Environment Variables');
} else if (SUPABASE_PUBLISHABLE_KEY.length < 50) {
  // Modern publishable keys (sb_publishable_...) are shorter than legacy anon keys
  // Check for both formats
  const isModernKey = SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_');
  const isLegacyKey = SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ');
  
  if (!isModernKey && !isLegacyKey) {
    console.warn('⚠️ VITE_SUPABASE_PUBLISHABLE_KEY format appears invalid.');
    console.warn('   Should start with "sb_publishable_" (modern) or "eyJ" (legacy anon key)');
    console.warn('   Get your key from: https://supabase.com/dashboard/project/flndlrgxxnlhuuusargv/settings/api');
  }
}

// Validate URL format
const isValidUrl = (url: string | undefined): boolean => {
  if (!url || typeof url !== 'string' || url.trim() === '') return false;
  try {
    const urlObj = new URL(url.trim());
    return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
  } catch {
    return false;
  }
};

// Validate that we have required environment variables
const hasValidUrl = isValidUrl(SUPABASE_URL);
const hasValidKey = SUPABASE_PUBLISHABLE_KEY && SUPABASE_PUBLISHABLE_KEY.trim().length > 0;

if (!hasValidUrl || !hasValidKey) {
  const missingVars: string[] = [];
  if (!hasValidUrl) {
    missingVars.push('VITE_SUPABASE_URL');
    console.error('❌ VITE_SUPABASE_URL is missing or invalid');
    console.error('   Current value:', SUPABASE_URL ? `"${SUPABASE_URL}"` : 'undefined');
  }
  if (!hasValidKey) {
    missingVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');
    console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY is missing or invalid');
    console.error('   Current value:', SUPABASE_PUBLISHABLE_KEY ? `"${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}..."` : 'undefined');
  }

  const errorMsg = `❌ Missing or invalid environment variables: ${missingVars.join(', ')}\n\n` +
    `🔧 How to fix:\n` +
    `  1. Go to Vercel Dashboard: https://vercel.com/dashboard\n` +
    `  2. Select your project\n` +
    `  3. Go to Settings > Environment Variables\n` +
    `  4. Add these variables:\n` +
    `     - VITE_SUPABASE_URL=https://your-project.supabase.co\n` +
    `     - VITE_SUPABASE_PUBLISHABLE_KEY=your-key-here\n` +
    `  5. Redeploy your project\n\n` +
    `📋 Get your values from: https://supabase.com/dashboard/project/YOUR_PROJECT_ID/settings/api\n\n` +
    `⚠️ Note: After adding variables, you MUST redeploy for changes to take effect!`;

  console.error(errorMsg);
  
  // Create a user-friendly error that will show in the browser
  const userFriendlyError = `Configuration Error: Missing environment variables (${missingVars.join(', ')}). ` +
    `Please check the browser console for detailed instructions.`;
  
  // Always throw to prevent creating invalid client
  throw new Error(userFriendlyError);
}

// Only create client if we have valid configuration
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL!.trim(),
  SUPABASE_PUBLISHABLE_KEY!.trim(),
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
